### ISSUE TITLE
worker大于1时，第一次启动报错

### ISSUE THREAD

**Issue by imweijh** [cgcel/SimplePaddleOCRApi#12]
首先感谢这个项目，docker部署很方便。
默认是一个CPU工作
在Dockerfile修改 workers 为 2 
`CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--workers", "2"]`

重新build令配置生效
` docker build -t paddleocrfastapi:latest  . `

`docker compose up`运行报错如下，但似乎不影响运行
```
[+] Running 1/1
 ✔ Container paddle_ocr_api  Recreated                                                                                                                   0.9s
Attaching to paddle_ocr_api
paddle_ocr_api  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
paddle_ocr_api  | INFO:     Started parent process [1]
paddle_ocr_api  | download https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar to /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_
PP-OCRv4_det_infer.tar
paddle_ocr_api  | download https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar to /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_
PP-OCRv4_det_infer.tar
100%|██████████| 4.89M/4.89M [00:43<00:00, 113kiB/s]
paddle_ocr_api  | Process SpawnProcess-2:
paddle_ocr_api  | Traceback (most recent call last):
paddle_ocr_api  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
paddle_ocr_api  |     self.run()
paddle_ocr_api  |   File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
paddle_ocr_api  |     self._target(*self._args, **self._kwargs)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
paddle_ocr_api  |     target(sockets=sockets)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
paddle_ocr_api  |     return asyncio.run(self.serve(sockets=sockets))
paddle_ocr_api  |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
paddle_ocr_api  |     return loop.run_until_complete(main)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
paddle_ocr_api  |     return future.result()
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
paddle_ocr_api  |     config.load()
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load
paddle_ocr_api  |     self.loaded_app = import_from_string(self.app)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
paddle_ocr_api  |     module = importlib.import_module(module_str)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
paddle_ocr_api  |     return _bootstrap._gcd_import(name[level:], package, level)
paddle_ocr_api  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
paddle_ocr_api  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
paddle_ocr_api  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
paddle_ocr_api  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
paddle_ocr_api  |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
paddle_ocr_api  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
paddle_ocr_api  |   File "/app/main.py", line 9, in <module>
paddle_ocr_api  |     from routers import ocr
paddle_ocr_api  |   File "/app/routers/ocr.py", line 15, in <module>
paddle_ocr_api  |     ocr = PaddleOCR(use_angle_cls=True, lang=OCR_LANGUAGE)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 596, in __init__
paddle_ocr_api  |     maybe_download(params.det_model_dir, det_url)
paddle_ocr_api  |   File "/usr/local/lib/python3.8/site-packages/paddleocr/ppocr/utils/network.py", line 69, in maybe_download
paddle_ocr_api  |     os.remove(tmp_path)
paddle_ocr_api  | FileNotFoundError: [Errno 2] No such file or directory: '/root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_PP-OCRv4_det_infer.tar'

```

`docker stats`  
观察 CPU 可以到200%
同时2个ocr请求也不会等待

**Comment by imweijh** [comment]
另外还修改了 docker-compose.yml  增加cups配置
```
services:

  PaddleOCR:
    build: .
    container_name: paddle_ocr_api # 自定义容器名
    image: paddleocrfastapi:latest # 第2步自定义的镜像名与标签
    deploy:
      resources:
        limits:
          cpus: '2.0'
    environment:
      - TZ=Asia/Hong_Kong
      - OCR_LANGUAGE=ch
      # - http_proxy=http://127.0.0.1:8888
      # - https_proxy=http://127.0.0.1:8888
    ports:
    - "8000:8000" # 自定义服务暴露端口, 8000为FastAPI默认端口, 不做修改,只能改前面的8000,不要忘了引号
    restart: unless-stopped

```
